// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class ApprovePostBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ApprovePostBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsApprovePostBody(bb:flatbuffers.ByteBuffer, obj?:ApprovePostBody):ApprovePostBody {
  return (obj || new ApprovePostBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsApprovePostBody(bb:flatbuffers.ByteBuffer, obj?:ApprovePostBody):ApprovePostBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ApprovePostBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

postId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.ApprovePostBody" {
  return 'mybroker.ApprovePostBody';
}

static startApprovePostBody(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPostId(builder:flatbuffers.Builder, postId:number) {
  builder.addFieldInt32(0, postId, 0);
}

static endApprovePostBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createApprovePostBody(builder:flatbuffers.Builder, postId:number):flatbuffers.Offset {
  ApprovePostBody.startApprovePostBody(builder);
  ApprovePostBody.addPostId(builder, postId);
  return ApprovePostBody.endApprovePostBody(builder);
}
}
