// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class ApproveUserBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ApproveUserBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsApproveUserBody(bb:flatbuffers.ByteBuffer, obj?:ApproveUserBody):ApproveUserBody {
  return (obj || new ApproveUserBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsApproveUserBody(bb:flatbuffers.ByteBuffer, obj?:ApproveUserBody):ApproveUserBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ApproveUserBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.ApproveUserBody" {
  return 'mybroker.ApproveUserBody';
}

static startApproveUserBody(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUserId(builder:flatbuffers.Builder, userId:number) {
  builder.addFieldInt32(0, userId, 0);
}

static endApproveUserBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createApproveUserBody(builder:flatbuffers.Builder, userId:number):flatbuffers.Offset {
  ApproveUserBody.startApproveUserBody(builder);
  ApproveUserBody.addUserId(builder, userId);
  return ApproveUserBody.endApproveUserBody(builder);
}
}
