// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { User } from '../mybroker/user';


export class AuthOk {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AuthOk {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAuthOk(bb:flatbuffers.ByteBuffer, obj?:AuthOk):AuthOk {
  return (obj || new AuthOk()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAuthOk(bb:flatbuffers.ByteBuffer, obj?:AuthOk):AuthOk {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AuthOk()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

user(obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static getFullyQualifiedName(): "mybroker.AuthOk" {
  return 'mybroker.AuthOk';
}

static startAuthOk(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUser(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userOffset, 0);
}

static endAuthOk(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAuthOk(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset):flatbuffers.Offset {
  AuthOk.startAuthOk(builder);
  AuthOk.addUser(builder, userOffset);
  return AuthOk.endAuthOk(builder);
}
}
