// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class BlockBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BlockBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBlockBody(bb:flatbuffers.ByteBuffer, obj?:BlockBody):BlockBody {
  return (obj || new BlockBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBlockBody(bb:flatbuffers.ByteBuffer, obj?:BlockBody):BlockBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BlockBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

blockedUserId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

blocked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "mybroker.BlockBody" {
  return 'mybroker.BlockBody';
}

static startBlockBody(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBlockedUserId(builder:flatbuffers.Builder, blockedUserId:number) {
  builder.addFieldInt32(0, blockedUserId, 0);
}

static addBlocked(builder:flatbuffers.Builder, blocked:boolean) {
  builder.addFieldInt8(1, +blocked, +false);
}

static endBlockBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBlockBody(builder:flatbuffers.Builder, blockedUserId:number, blocked:boolean):flatbuffers.Offset {
  BlockBody.startBlockBody(builder);
  BlockBody.addBlockedUserId(builder, blockedUserId);
  BlockBody.addBlocked(builder, blocked);
  return BlockBody.endBlockBody(builder);
}
}
