// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { PostWire } from '../mybroker/post-wire';


export class ChatMsg {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatMsg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatMsg(bb:flatbuffers.ByteBuffer, obj?:ChatMsg):ChatMsg {
  return (obj || new ChatMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatMsg(bb:flatbuffers.ByteBuffer, obj?:ChatMsg):ChatMsg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

image():string|null
image(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
image(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

post(obj?:PostWire):PostWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PostWire()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

createdAtUnixMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

seenByRecipient():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isOwnedByRecipient():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "mybroker.ChatMsg" {
  return 'mybroker.ChatMsg';
}

static startChatMsg(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, textOffset, 0);
}

static addImage(builder:flatbuffers.Builder, imageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, imageOffset, 0);
}

static addPost(builder:flatbuffers.Builder, postOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, postOffset, 0);
}

static addCreatedAtUnixMs(builder:flatbuffers.Builder, createdAtUnixMs:bigint) {
  builder.addFieldInt64(4, createdAtUnixMs, BigInt('0'));
}

static addSeenByRecipient(builder:flatbuffers.Builder, seenByRecipient:boolean) {
  builder.addFieldInt8(5, +seenByRecipient, +false);
}

static addIsOwnedByRecipient(builder:flatbuffers.Builder, isOwnedByRecipient:boolean) {
  builder.addFieldInt8(6, +isOwnedByRecipient, +false);
}

static endChatMsg(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
