// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { ChatRow } from '../mybroker/chat-row';


export class ChatRowList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatRowList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatRowList(bb:flatbuffers.ByteBuffer, obj?:ChatRowList):ChatRowList {
  return (obj || new ChatRowList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatRowList(bb:flatbuffers.ByteBuffer, obj?:ChatRowList):ChatRowList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatRowList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

chats(index: number, obj?:ChatRow):ChatRow|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ChatRow()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

chatsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.ChatRowList" {
  return 'mybroker.ChatRowList';
}

static startChatRowList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addChats(builder:flatbuffers.Builder, chatsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, chatsOffset, 0);
}

static createChatsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChatsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endChatRowList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatRowList(builder:flatbuffers.Builder, chatsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ChatRowList.startChatRowList(builder);
  ChatRowList.addChats(builder, chatsOffset);
  return ChatRowList.endChatRowList(builder);
}
}
