// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { User } from '../mybroker/user';


export class ChatRow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatRow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatRow(bb:flatbuffers.ByteBuffer, obj?:ChatRow):ChatRow {
  return (obj || new ChatRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatRow(bb:flatbuffers.ByteBuffer, obj?:ChatRow):ChatRow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

user(obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

lastMessage():string|null
lastMessage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastMessage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

newMessages():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.ChatRow" {
  return 'mybroker.ChatRow';
}

static startChatRow(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addUser(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, userOffset, 0);
}

static addLastMessage(builder:flatbuffers.Builder, lastMessageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, lastMessageOffset, 0);
}

static addNewMessages(builder:flatbuffers.Builder, newMessages:number) {
  builder.addFieldInt32(3, newMessages, 0);
}

static endChatRow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
