// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class ChatsAndFavs {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatsAndFavs {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatsAndFavs(bb:flatbuffers.ByteBuffer, obj?:ChatsAndFavs):ChatsAndFavs {
  return (obj || new ChatsAndFavs()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatsAndFavs(bb:flatbuffers.ByteBuffer, obj?:ChatsAndFavs):ChatsAndFavs {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatsAndFavs()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

unreadTotal():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

favourites():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.ChatsAndFavs" {
  return 'mybroker.ChatsAndFavs';
}

static startChatsAndFavs(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addUnreadTotal(builder:flatbuffers.Builder, unreadTotal:number) {
  builder.addFieldInt32(0, unreadTotal, 0);
}

static addFavourites(builder:flatbuffers.Builder, favourites:number) {
  builder.addFieldInt32(1, favourites, 0);
}

static endChatsAndFavs(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatsAndFavs(builder:flatbuffers.Builder, unreadTotal:number, favourites:number):flatbuffers.Offset {
  ChatsAndFavs.startChatsAndFavs(builder);
  ChatsAndFavs.addUnreadTotal(builder, unreadTotal);
  ChatsAndFavs.addFavourites(builder, favourites);
  return ChatsAndFavs.endChatsAndFavs(builder);
}
}
