// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class ConfirmEmailChangeBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConfirmEmailChangeBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConfirmEmailChangeBody(bb:flatbuffers.ByteBuffer, obj?:ConfirmEmailChangeBody):ConfirmEmailChangeBody {
  return (obj || new ConfirmEmailChangeBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConfirmEmailChangeBody(bb:flatbuffers.ByteBuffer, obj?:ConfirmEmailChangeBody):ConfirmEmailChangeBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConfirmEmailChangeBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

email():string|null
email(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
email(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

otp():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.ConfirmEmailChangeBody" {
  return 'mybroker.ConfirmEmailChangeBody';
}

static startConfirmEmailChangeBody(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEmail(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, emailOffset, 0);
}

static addOtp(builder:flatbuffers.Builder, otp:number) {
  builder.addFieldInt32(1, otp, 0);
}

static endConfirmEmailChangeBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConfirmEmailChangeBody(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset, otp:number):flatbuffers.Offset {
  ConfirmEmailChangeBody.startConfirmEmailChangeBody(builder);
  ConfirmEmailChangeBody.addEmail(builder, emailOffset);
  ConfirmEmailChangeBody.addOtp(builder, otp);
  return ConfirmEmailChangeBody.endConfirmEmailChangeBody(builder);
}
}
