// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class ConfirmPinResetBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConfirmPinResetBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConfirmPinResetBody(bb:flatbuffers.ByteBuffer, obj?:ConfirmPinResetBody):ConfirmPinResetBody {
  return (obj || new ConfirmPinResetBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConfirmPinResetBody(bb:flatbuffers.ByteBuffer, obj?:ConfirmPinResetBody):ConfirmPinResetBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConfirmPinResetBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

phoneNumber():string|null
phoneNumber(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
phoneNumber(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

otp():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

pin():string|null
pin(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pin(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pinConfirm():string|null
pinConfirm(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pinConfirm(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.ConfirmPinResetBody" {
  return 'mybroker.ConfirmPinResetBody';
}

static startConfirmPinResetBody(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addPhoneNumber(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, phoneNumberOffset, 0);
}

static addOtp(builder:flatbuffers.Builder, otp:number) {
  builder.addFieldInt32(1, otp, 0);
}

static addPin(builder:flatbuffers.Builder, pinOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, pinOffset, 0);
}

static addPinConfirm(builder:flatbuffers.Builder, pinConfirmOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, pinConfirmOffset, 0);
}

static endConfirmPinResetBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConfirmPinResetBody(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset, otp:number, pinOffset:flatbuffers.Offset, pinConfirmOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConfirmPinResetBody.startConfirmPinResetBody(builder);
  ConfirmPinResetBody.addPhoneNumber(builder, phoneNumberOffset);
  ConfirmPinResetBody.addOtp(builder, otp);
  ConfirmPinResetBody.addPin(builder, pinOffset);
  ConfirmPinResetBody.addPinConfirm(builder, pinConfirmOffset);
  return ConfirmPinResetBody.endConfirmPinResetBody(builder);
}
}
