// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { Location } from '../mybroker/location';
import { Price } from '../mybroker/price';


export class CreatePostBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreatePostBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreatePostBody(bb:flatbuffers.ByteBuffer, obj?:CreatePostBody):CreatePostBody {
  return (obj || new CreatePostBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreatePostBody(bb:flatbuffers.ByteBuffer, obj?:CreatePostBody):CreatePostBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreatePostBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

payWaterBills():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

payElectricityBills():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

payForTrash():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

hasParking():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

requiredFirstMonthsPaid():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

units():string|null
units(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
units(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isNegotiable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

reviewDisclaimerAgreed():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

price(obj?:Price):Price|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new Price()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

location(obj?:Location):Location|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new Location()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

bedrooms():string|null
bedrooms(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
bedrooms(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

bathrooms():string|null
bathrooms(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
bathrooms(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

toilets():string|null
toilets(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
toilets(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

images(index: number):string
images(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
images(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

imagesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

amenities():string|null
amenities(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
amenities(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.CreatePostBody" {
  return 'mybroker.CreatePostBody';
}

static startCreatePostBody(builder:flatbuffers.Builder) {
  builder.startObject(16);
}

static addPayWaterBills(builder:flatbuffers.Builder, payWaterBills:boolean) {
  builder.addFieldInt8(0, +payWaterBills, +false);
}

static addPayElectricityBills(builder:flatbuffers.Builder, payElectricityBills:boolean) {
  builder.addFieldInt8(1, +payElectricityBills, +false);
}

static addPayForTrash(builder:flatbuffers.Builder, payForTrash:boolean) {
  builder.addFieldInt8(2, +payForTrash, +false);
}

static addHasParking(builder:flatbuffers.Builder, hasParking:boolean) {
  builder.addFieldInt8(3, +hasParking, +false);
}

static addRequiredFirstMonthsPaid(builder:flatbuffers.Builder, requiredFirstMonthsPaid:number) {
  builder.addFieldInt32(4, requiredFirstMonthsPaid, 0);
}

static addUnits(builder:flatbuffers.Builder, unitsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, unitsOffset, 0);
}

static addIsNegotiable(builder:flatbuffers.Builder, isNegotiable:boolean) {
  builder.addFieldInt8(6, +isNegotiable, +false);
}

static addReviewDisclaimerAgreed(builder:flatbuffers.Builder, reviewDisclaimerAgreed:boolean) {
  builder.addFieldInt8(7, +reviewDisclaimerAgreed, +false);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, typeOffset, 0);
}

static addPrice(builder:flatbuffers.Builder, priceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, priceOffset, 0);
}

static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, locationOffset, 0);
}

static addBedrooms(builder:flatbuffers.Builder, bedroomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, bedroomsOffset, 0);
}

static addBathrooms(builder:flatbuffers.Builder, bathroomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, bathroomsOffset, 0);
}

static addToilets(builder:flatbuffers.Builder, toiletsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, toiletsOffset, 0);
}

static addImages(builder:flatbuffers.Builder, imagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, imagesOffset, 0);
}

static createImagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startImagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addAmenities(builder:flatbuffers.Builder, amenitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(15, amenitiesOffset, 0);
}

static endCreatePostBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
