// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class EmptyReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EmptyReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEmptyReq(bb:flatbuffers.ByteBuffer, obj?:EmptyReq):EmptyReq {
  return (obj || new EmptyReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEmptyReq(bb:flatbuffers.ByteBuffer, obj?:EmptyReq):EmptyReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EmptyReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getFullyQualifiedName(): "mybroker.EmptyReq" {
  return 'mybroker.EmptyReq';
}

static startEmptyReq(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endEmptyReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEmptyReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  EmptyReq.startEmptyReq(builder);
  return EmptyReq.endEmptyReq(builder);
}
}
