// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars */

import * as flatbuffers from 'flatbuffers';

import { ApiPayload, unionToApiPayload, unionListToApiPayload } from '../mybroker/api-payload';


export class Envelope {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Envelope {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEnvelope(bb:flatbuffers.ByteBuffer, obj?:Envelope):Envelope {
  return (obj || new Envelope()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEnvelope(bb:flatbuffers.ByteBuffer, obj?:Envelope):Envelope {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Envelope()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

httpStatus():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

msg():string|null
msg(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
msg(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

token():string|null
token(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
token(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

otp():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

warning():string|null
warning(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
warning(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

payloadType():ApiPayload {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ApiPayload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static getFullyQualifiedName(): "mybroker.Envelope" {
  return 'mybroker.Envelope';
}

static startEnvelope(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addHttpStatus(builder:flatbuffers.Builder, httpStatus:number) {
  builder.addFieldInt32(0, httpStatus, 0);
}

static addMsg(builder:flatbuffers.Builder, msgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, msgOffset, 0);
}

static addToken(builder:flatbuffers.Builder, tokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, tokenOffset, 0);
}

static addOtp(builder:flatbuffers.Builder, otp:number) {
  builder.addFieldInt32(3, otp, 0);
}

static addWarning(builder:flatbuffers.Builder, warningOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, warningOffset, 0);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:ApiPayload) {
  builder.addFieldInt8(5, payloadType, ApiPayload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, payloadOffset, 0);
}

static endEnvelope(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishEnvelopeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedEnvelopeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createEnvelope(builder:flatbuffers.Builder, httpStatus:number, msgOffset:flatbuffers.Offset, tokenOffset:flatbuffers.Offset, otp:number, warningOffset:flatbuffers.Offset, payloadType:ApiPayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Envelope.startEnvelope(builder);
  Envelope.addHttpStatus(builder, httpStatus);
  Envelope.addMsg(builder, msgOffset);
  Envelope.addToken(builder, tokenOffset);
  Envelope.addOtp(builder, otp);
  Envelope.addWarning(builder, warningOffset);
  Envelope.addPayloadType(builder, payloadType);
  Envelope.addPayload(builder, payloadOffset);
  return Envelope.endEnvelope(builder);
}
}
