// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class GoogleAuthBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GoogleAuthBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGoogleAuthBody(bb:flatbuffers.ByteBuffer, obj?:GoogleAuthBody):GoogleAuthBody {
  return (obj || new GoogleAuthBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGoogleAuthBody(bb:flatbuffers.ByteBuffer, obj?:GoogleAuthBody):GoogleAuthBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GoogleAuthBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

accessToken():string|null
accessToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
accessToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

idToken():string|null
idToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
idToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.GoogleAuthBody" {
  return 'mybroker.GoogleAuthBody';
}

static startGoogleAuthBody(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addAccessToken(builder:flatbuffers.Builder, accessTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, accessTokenOffset, 0);
}

static addIdToken(builder:flatbuffers.Builder, idTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, idTokenOffset, 0);
}

static endGoogleAuthBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGoogleAuthBody(builder:flatbuffers.Builder, accessTokenOffset:flatbuffers.Offset, idTokenOffset:flatbuffers.Offset):flatbuffers.Offset {
  GoogleAuthBody.startGoogleAuthBody(builder);
  GoogleAuthBody.addAccessToken(builder, accessTokenOffset);
  GoogleAuthBody.addIdToken(builder, idTokenOffset);
  return GoogleAuthBody.endGoogleAuthBody(builder);
}
}
