// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { Location } from '../mybroker/location';
import { NestedUser } from '../mybroker/nested-user';
import { Price } from '../mybroker/price';


export class NestedPostT {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NestedPostT {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNestedPostT(bb:flatbuffers.ByteBuffer, obj?:NestedPostT):NestedPostT {
  return (obj || new NestedPostT()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNestedPostT(bb:flatbuffers.ByteBuffer, obj?:NestedPostT):NestedPostT {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NestedPostT()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

idDup():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

price(obj?:Price):Price|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Price()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

location(obj?:Location):Location|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Location()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

isLiked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isNegotiable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

bedrooms():string|null
bedrooms(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
bedrooms(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

bathrooms():string|null
bathrooms(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
bathrooms(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

toilets():string|null
toilets(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
toilets(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

images(index: number):string
images(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
images(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

imagesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

author(obj?:NestedUser):NestedUser|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new NestedUser()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

user(obj?:NestedUser):NestedUser|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new NestedUser()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

likers(index: number, obj?:NestedUser):NestedUser|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? (obj || new NestedUser()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

likersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

hideUserInfo():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

selected():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isAvailable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "mybroker.NestedPostT" {
  return 'mybroker.NestedPostT';
}

static startNestedPostT(builder:flatbuffers.Builder) {
  builder.startObject(17);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addIdDup(builder:flatbuffers.Builder, idDup:number) {
  builder.addFieldInt32(1, idDup, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, typeOffset, 0);
}

static addPrice(builder:flatbuffers.Builder, priceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, priceOffset, 0);
}

static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, locationOffset, 0);
}

static addIsLiked(builder:flatbuffers.Builder, isLiked:boolean) {
  builder.addFieldInt8(5, +isLiked, +false);
}

static addIsNegotiable(builder:flatbuffers.Builder, isNegotiable:boolean) {
  builder.addFieldInt8(6, +isNegotiable, +false);
}

static addBedrooms(builder:flatbuffers.Builder, bedroomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, bedroomsOffset, 0);
}

static addBathrooms(builder:flatbuffers.Builder, bathroomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, bathroomsOffset, 0);
}

static addToilets(builder:flatbuffers.Builder, toiletsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, toiletsOffset, 0);
}

static addImages(builder:flatbuffers.Builder, imagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, imagesOffset, 0);
}

static createImagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startImagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addAuthor(builder:flatbuffers.Builder, authorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, authorOffset, 0);
}

static addUser(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, userOffset, 0);
}

static addLikers(builder:flatbuffers.Builder, likersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, likersOffset, 0);
}

static createLikersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLikersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHideUserInfo(builder:flatbuffers.Builder, hideUserInfo:boolean) {
  builder.addFieldInt8(14, +hideUserInfo, +false);
}

static addSelected(builder:flatbuffers.Builder, selected:boolean) {
  builder.addFieldInt8(15, +selected, +false);
}

static addIsAvailable(builder:flatbuffers.Builder, isAvailable:boolean) {
  builder.addFieldInt8(16, +isAvailable, +false);
}

static endNestedPostT(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
