// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

/**
 * Phone auth: `pin_confirm` empty = login; non-empty = create or first-time set PIN (must match `pin`).
 */
export class PhonePinBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PhonePinBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPhonePinBody(bb:flatbuffers.ByteBuffer, obj?:PhonePinBody):PhonePinBody {
  return (obj || new PhonePinBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPhonePinBody(bb:flatbuffers.ByteBuffer, obj?:PhonePinBody):PhonePinBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PhonePinBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

phoneNumber():string|null
phoneNumber(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
phoneNumber(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pin():string|null
pin(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pin(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pinConfirm():string|null
pinConfirm(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pinConfirm(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.PhonePinBody" {
  return 'mybroker.PhonePinBody';
}

static startPhonePinBody(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPhoneNumber(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, phoneNumberOffset, 0);
}

static addPin(builder:flatbuffers.Builder, pinOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, pinOffset, 0);
}

static addPinConfirm(builder:flatbuffers.Builder, pinConfirmOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, pinConfirmOffset, 0);
}

static endPhonePinBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPhonePinBody(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset, pinOffset:flatbuffers.Offset, pinConfirmOffset:flatbuffers.Offset):flatbuffers.Offset {
  PhonePinBody.startPhonePinBody(builder);
  PhonePinBody.addPhoneNumber(builder, phoneNumberOffset);
  PhonePinBody.addPin(builder, pinOffset);
  PhonePinBody.addPinConfirm(builder, pinConfirmOffset);
  return PhonePinBody.endPhonePinBody(builder);
}
}
