// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class PinResetResolveBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PinResetResolveBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPinResetResolveBody(bb:flatbuffers.ByteBuffer, obj?:PinResetResolveBody):PinResetResolveBody {
  return (obj || new PinResetResolveBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPinResetResolveBody(bb:flatbuffers.ByteBuffer, obj?:PinResetResolveBody):PinResetResolveBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PinResetResolveBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.PinResetResolveBody" {
  return 'mybroker.PinResetResolveBody';
}

static startPinResetResolveBody(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRequestId(builder:flatbuffers.Builder, requestId:number) {
  builder.addFieldInt32(0, requestId, 0);
}

static endPinResetResolveBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPinResetResolveBody(builder:flatbuffers.Builder, requestId:number):flatbuffers.Offset {
  PinResetResolveBody.startPinResetResolveBody(builder);
  PinResetResolveBody.addRequestId(builder, requestId);
  return PinResetResolveBody.endPinResetResolveBody(builder);
}
}
