// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class PostLocationRow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostLocationRow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostLocationRow(bb:flatbuffers.ByteBuffer, obj?:PostLocationRow):PostLocationRow {
  return (obj || new PostLocationRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostLocationRow(bb:flatbuffers.ByteBuffer, obj?:PostLocationRow):PostLocationRow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostLocationRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

latitude():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

longitude():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

price():string|null
price(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
price(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

address():string|null
address(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
address(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.PostLocationRow" {
  return 'mybroker.PostLocationRow';
}

static startPostLocationRow(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addLatitude(builder:flatbuffers.Builder, latitude:number) {
  builder.addFieldFloat64(1, latitude, 0.0);
}

static addLongitude(builder:flatbuffers.Builder, longitude:number) {
  builder.addFieldFloat64(2, longitude, 0.0);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, titleOffset, 0);
}

static addPrice(builder:flatbuffers.Builder, priceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, priceOffset, 0);
}

static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, addressOffset, 0);
}

static endPostLocationRow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPostLocationRow(builder:flatbuffers.Builder, id:number, latitude:number, longitude:number, titleOffset:flatbuffers.Offset, priceOffset:flatbuffers.Offset, addressOffset:flatbuffers.Offset):flatbuffers.Offset {
  PostLocationRow.startPostLocationRow(builder);
  PostLocationRow.addId(builder, id);
  PostLocationRow.addLatitude(builder, latitude);
  PostLocationRow.addLongitude(builder, longitude);
  PostLocationRow.addTitle(builder, titleOffset);
  PostLocationRow.addPrice(builder, priceOffset);
  PostLocationRow.addAddress(builder, addressOffset);
  return PostLocationRow.endPostLocationRow(builder);
}
}
