// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { PostWire } from '../mybroker/post-wire';


export class PostPage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostPage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostPage(bb:flatbuffers.ByteBuffer, obj?:PostPage):PostPage {
  return (obj || new PostPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostPage(bb:flatbuffers.ByteBuffer, obj?:PostPage):PostPage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostPage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

posts(index: number, obj?:PostWire):PostWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PostWire()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

postsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

total():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

page():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

limit():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.PostPage" {
  return 'mybroker.PostPage';
}

static startPostPage(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addPosts(builder:flatbuffers.Builder, postsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, postsOffset, 0);
}

static createPostsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPostsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTotal(builder:flatbuffers.Builder, total:bigint) {
  builder.addFieldInt64(1, total, BigInt('0'));
}

static addPage(builder:flatbuffers.Builder, page:number) {
  builder.addFieldInt32(2, page, 0);
}

static addLimit(builder:flatbuffers.Builder, limit:number) {
  builder.addFieldInt32(3, limit, 0);
}

static endPostPage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPostPage(builder:flatbuffers.Builder, postsOffset:flatbuffers.Offset, total:bigint, page:number, limit:number):flatbuffers.Offset {
  PostPage.startPostPage(builder);
  PostPage.addPosts(builder, postsOffset);
  PostPage.addTotal(builder, total);
  PostPage.addPage(builder, page);
  PostPage.addLimit(builder, limit);
  return PostPage.endPostPage(builder);
}
}
