// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class PostIdBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostIdBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostIdBody(bb:flatbuffers.ByteBuffer, obj?:PostIdBody):PostIdBody {
  return (obj || new PostIdBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostIdBody(bb:flatbuffers.ByteBuffer, obj?:PostIdBody):PostIdBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostIdBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

postId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.PostIdBody" {
  return 'mybroker.PostIdBody';
}

static startPostIdBody(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPostId(builder:flatbuffers.Builder, postId:number) {
  builder.addFieldInt32(0, postId, 0);
}

static endPostIdBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPostIdBody(builder:flatbuffers.Builder, postId:number):flatbuffers.Offset {
  PostIdBody.startPostIdBody(builder);
  PostIdBody.addPostId(builder, postId);
  return PostIdBody.endPostIdBody(builder);
}
}
