// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { Location } from '../mybroker/location';
import { Price } from '../mybroker/price';
import { User } from '../mybroker/user';


export class PostWire {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostWire {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostWire(bb:flatbuffers.ByteBuffer, obj?:PostWire):PostWire {
  return (obj || new PostWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostWire(bb:flatbuffers.ByteBuffer, obj?:PostWire):PostWire {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostWire()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

userId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

price(obj?:Price):Price|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Price()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

location(obj?:Location):Location|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Location()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

bedrooms():string|null
bedrooms(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
bedrooms(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

bathrooms():string|null
bathrooms(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
bathrooms(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

toilets():string|null
toilets(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
toilets(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

images(index: number):string
images(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
images(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

imagesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

amenities():string|null
amenities(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
amenities(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

payWaterBills():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

payElectricityBills():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

payForTrash():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

hasParking():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

requiredFirstMonthsPaid():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

units():string|null
units(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
units(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isNegotiable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isApproved():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

reviewDisclaimerAgreed():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

user(obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

likers(index: number, obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

likersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

isAvailable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "mybroker.PostWire" {
  return 'mybroker.PostWire';
}

static startPostWire(builder:flatbuffers.Builder) {
  builder.startObject(22);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addUserId(builder:flatbuffers.Builder, userId:number) {
  builder.addFieldInt32(1, userId, 0);
}

static addPrice(builder:flatbuffers.Builder, priceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, priceOffset, 0);
}

static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, locationOffset, 0);
}

static addBedrooms(builder:flatbuffers.Builder, bedroomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, bedroomsOffset, 0);
}

static addBathrooms(builder:flatbuffers.Builder, bathroomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, bathroomsOffset, 0);
}

static addToilets(builder:flatbuffers.Builder, toiletsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, toiletsOffset, 0);
}

static addImages(builder:flatbuffers.Builder, imagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, imagesOffset, 0);
}

static createImagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startImagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addAmenities(builder:flatbuffers.Builder, amenitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, amenitiesOffset, 0);
}

static addPayWaterBills(builder:flatbuffers.Builder, payWaterBills:boolean) {
  builder.addFieldInt8(9, +payWaterBills, +false);
}

static addPayElectricityBills(builder:flatbuffers.Builder, payElectricityBills:boolean) {
  builder.addFieldInt8(10, +payElectricityBills, +false);
}

static addPayForTrash(builder:flatbuffers.Builder, payForTrash:boolean) {
  builder.addFieldInt8(11, +payForTrash, +false);
}

static addHasParking(builder:flatbuffers.Builder, hasParking:boolean) {
  builder.addFieldInt8(12, +hasParking, +false);
}

static addRequiredFirstMonthsPaid(builder:flatbuffers.Builder, requiredFirstMonthsPaid:number) {
  builder.addFieldInt32(13, requiredFirstMonthsPaid, 0);
}

static addUnits(builder:flatbuffers.Builder, unitsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, unitsOffset, 0);
}

static addIsNegotiable(builder:flatbuffers.Builder, isNegotiable:boolean) {
  builder.addFieldInt8(15, +isNegotiable, +false);
}

static addIsApproved(builder:flatbuffers.Builder, isApproved:boolean) {
  builder.addFieldInt8(16, +isApproved, +false);
}

static addReviewDisclaimerAgreed(builder:flatbuffers.Builder, reviewDisclaimerAgreed:boolean) {
  builder.addFieldInt8(17, +reviewDisclaimerAgreed, +false);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(18, typeOffset, 0);
}

static addUser(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset) {
  builder.addFieldOffset(19, userOffset, 0);
}

static addLikers(builder:flatbuffers.Builder, likersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(20, likersOffset, 0);
}

static createLikersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLikersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addIsAvailable(builder:flatbuffers.Builder, isAvailable:boolean) {
  builder.addFieldInt8(21, +isAvailable, +false);
}

static endPostWire(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
