// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { PostLocationRow } from '../mybroker/post-location-row';


export class PostLocationList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostLocationList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostLocationList(bb:flatbuffers.ByteBuffer, obj?:PostLocationList):PostLocationList {
  return (obj || new PostLocationList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostLocationList(bb:flatbuffers.ByteBuffer, obj?:PostLocationList):PostLocationList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostLocationList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

items(index: number, obj?:PostLocationRow):PostLocationRow|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PostLocationRow()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.PostLocationList" {
  return 'mybroker.PostLocationList';
}

static startPostLocationList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPostLocationList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPostLocationList(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset):flatbuffers.Offset {
  PostLocationList.startPostLocationList(builder);
  PostLocationList.addItems(builder, itemsOffset);
  return PostLocationList.endPostLocationList(builder);
}
}
