// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { PostWire } from '../mybroker/post-wire';


export class PostList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostList(bb:flatbuffers.ByteBuffer, obj?:PostList):PostList {
  return (obj || new PostList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostList(bb:flatbuffers.ByteBuffer, obj?:PostList):PostList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

posts(index: number, obj?:PostWire):PostWire|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PostWire()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

postsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.PostList" {
  return 'mybroker.PostList';
}

static startPostList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPosts(builder:flatbuffers.Builder, postsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, postsOffset, 0);
}

static createPostsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPostsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPostList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPostList(builder:flatbuffers.Builder, postsOffset:flatbuffers.Offset):flatbuffers.Offset {
  PostList.startPostList(builder);
  PostList.addPosts(builder, postsOffset);
  return PostList.endPostList(builder);
}
}
