// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class Price {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Price {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPrice(bb:flatbuffers.ByteBuffer, obj?:Price):Price {
  return (obj || new Price()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPrice(bb:flatbuffers.ByteBuffer, obj?:Price):Price {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Price()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

currency():string|null
currency(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currency(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

amount():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.Price" {
  return 'mybroker.Price';
}

static startPrice(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCurrency(builder:flatbuffers.Builder, currencyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, currencyOffset, 0);
}

static addAmount(builder:flatbuffers.Builder, amount:number) {
  builder.addFieldInt32(1, amount, 0);
}

static endPrice(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPrice(builder:flatbuffers.Builder, currencyOffset:flatbuffers.Offset, amount:number):flatbuffers.Offset {
  Price.startPrice(builder);
  Price.addCurrency(builder, currencyOffset);
  Price.addAmount(builder, amount);
  return Price.endPrice(builder);
}
}
