// automatically generated by the FlatBuffers compiler, do not modify

 

import { ApprovePostBody } from '../mybroker/approve-post-body';
import { ApproveUserBody } from '../mybroker/approve-user-body';
import { BlockBody } from '../mybroker/block-body';
import { ConfirmEmailChangeBody } from '../mybroker/confirm-email-change-body';
import { ConfirmPinResetBody } from '../mybroker/confirm-pin-reset-body';
import { CreatePostBody } from '../mybroker/create-post-body';
import { EmptyReq } from '../mybroker/empty-req';
import { GoogleAuthBody } from '../mybroker/google-auth-body';
import { PhonePinBody } from '../mybroker/phone-pin-body';
import { PinResetResolveBody } from '../mybroker/pin-reset-resolve-body';
import { PostIdBody } from '../mybroker/post-id-body';
import { ReportBody } from '../mybroker/report-body';
import { RequestEmailChangeBody } from '../mybroker/request-email-change-body';
import { RequestPinResetBody } from '../mybroker/request-pin-reset-body';
import { RoomIdBody } from '../mybroker/room-id-body';
import { SignInPhone } from '../mybroker/sign-in-phone';
import { UpdateIdBody } from '../mybroker/update-id-body';
import { UpdateProfileBody } from '../mybroker/update-profile-body';
import { VerifyOtpBody } from '../mybroker/verify-otp-body';


export enum ReqPayload {
  NONE = 0,
  SignInPhone = 1,
  VerifyOtpBody = 2,
  GoogleAuthBody = 3,
  CreatePostBody = 4,
  UpdateProfileBody = 5,
  BlockBody = 6,
  ReportBody = 7,
  RoomIdBody = 8,
  PostIdBody = 9,
  ApprovePostBody = 10,
  ApproveUserBody = 11,
  UpdateIdBody = 12,
  PhonePinBody = 13,
  RequestPinResetBody = 14,
  ConfirmPinResetBody = 15,
  RequestEmailChangeBody = 16,
  ConfirmEmailChangeBody = 17,
  PinResetResolveBody = 18,
  EmptyReq = 19
}

export function unionToReqPayload(
  type: ReqPayload,
  accessor: (obj:ApprovePostBody|ApproveUserBody|BlockBody|ConfirmEmailChangeBody|ConfirmPinResetBody|CreatePostBody|EmptyReq|GoogleAuthBody|PhonePinBody|PinResetResolveBody|PostIdBody|ReportBody|RequestEmailChangeBody|RequestPinResetBody|RoomIdBody|SignInPhone|UpdateIdBody|UpdateProfileBody|VerifyOtpBody) => ApprovePostBody|ApproveUserBody|BlockBody|ConfirmEmailChangeBody|ConfirmPinResetBody|CreatePostBody|EmptyReq|GoogleAuthBody|PhonePinBody|PinResetResolveBody|PostIdBody|ReportBody|RequestEmailChangeBody|RequestPinResetBody|RoomIdBody|SignInPhone|UpdateIdBody|UpdateProfileBody|VerifyOtpBody|null
): ApprovePostBody|ApproveUserBody|BlockBody|ConfirmEmailChangeBody|ConfirmPinResetBody|CreatePostBody|EmptyReq|GoogleAuthBody|PhonePinBody|PinResetResolveBody|PostIdBody|ReportBody|RequestEmailChangeBody|RequestPinResetBody|RoomIdBody|SignInPhone|UpdateIdBody|UpdateProfileBody|VerifyOtpBody|null {
  switch(ReqPayload[type]) {
    case 'NONE': return null; 
    case 'SignInPhone': return accessor(new SignInPhone())! as SignInPhone;
    case 'VerifyOtpBody': return accessor(new VerifyOtpBody())! as VerifyOtpBody;
    case 'GoogleAuthBody': return accessor(new GoogleAuthBody())! as GoogleAuthBody;
    case 'CreatePostBody': return accessor(new CreatePostBody())! as CreatePostBody;
    case 'UpdateProfileBody': return accessor(new UpdateProfileBody())! as UpdateProfileBody;
    case 'BlockBody': return accessor(new BlockBody())! as BlockBody;
    case 'ReportBody': return accessor(new ReportBody())! as ReportBody;
    case 'RoomIdBody': return accessor(new RoomIdBody())! as RoomIdBody;
    case 'PostIdBody': return accessor(new PostIdBody())! as PostIdBody;
    case 'ApprovePostBody': return accessor(new ApprovePostBody())! as ApprovePostBody;
    case 'ApproveUserBody': return accessor(new ApproveUserBody())! as ApproveUserBody;
    case 'UpdateIdBody': return accessor(new UpdateIdBody())! as UpdateIdBody;
    case 'PhonePinBody': return accessor(new PhonePinBody())! as PhonePinBody;
    case 'RequestPinResetBody': return accessor(new RequestPinResetBody())! as RequestPinResetBody;
    case 'ConfirmPinResetBody': return accessor(new ConfirmPinResetBody())! as ConfirmPinResetBody;
    case 'RequestEmailChangeBody': return accessor(new RequestEmailChangeBody())! as RequestEmailChangeBody;
    case 'ConfirmEmailChangeBody': return accessor(new ConfirmEmailChangeBody())! as ConfirmEmailChangeBody;
    case 'PinResetResolveBody': return accessor(new PinResetResolveBody())! as PinResetResolveBody;
    case 'EmptyReq': return accessor(new EmptyReq())! as EmptyReq;
    default: return null;
  }
}

export function unionListToReqPayload(
  type: ReqPayload, 
  accessor: (index: number, obj:ApprovePostBody|ApproveUserBody|BlockBody|ConfirmEmailChangeBody|ConfirmPinResetBody|CreatePostBody|EmptyReq|GoogleAuthBody|PhonePinBody|PinResetResolveBody|PostIdBody|ReportBody|RequestEmailChangeBody|RequestPinResetBody|RoomIdBody|SignInPhone|UpdateIdBody|UpdateProfileBody|VerifyOtpBody) => ApprovePostBody|ApproveUserBody|BlockBody|ConfirmEmailChangeBody|ConfirmPinResetBody|CreatePostBody|EmptyReq|GoogleAuthBody|PhonePinBody|PinResetResolveBody|PostIdBody|ReportBody|RequestEmailChangeBody|RequestPinResetBody|RoomIdBody|SignInPhone|UpdateIdBody|UpdateProfileBody|VerifyOtpBody|null, 
  index: number
): ApprovePostBody|ApproveUserBody|BlockBody|ConfirmEmailChangeBody|ConfirmPinResetBody|CreatePostBody|EmptyReq|GoogleAuthBody|PhonePinBody|PinResetResolveBody|PostIdBody|ReportBody|RequestEmailChangeBody|RequestPinResetBody|RoomIdBody|SignInPhone|UpdateIdBody|UpdateProfileBody|VerifyOtpBody|null {
  switch(ReqPayload[type]) {
    case 'NONE': return null; 
    case 'SignInPhone': return accessor(index, new SignInPhone())! as SignInPhone;
    case 'VerifyOtpBody': return accessor(index, new VerifyOtpBody())! as VerifyOtpBody;
    case 'GoogleAuthBody': return accessor(index, new GoogleAuthBody())! as GoogleAuthBody;
    case 'CreatePostBody': return accessor(index, new CreatePostBody())! as CreatePostBody;
    case 'UpdateProfileBody': return accessor(index, new UpdateProfileBody())! as UpdateProfileBody;
    case 'BlockBody': return accessor(index, new BlockBody())! as BlockBody;
    case 'ReportBody': return accessor(index, new ReportBody())! as ReportBody;
    case 'RoomIdBody': return accessor(index, new RoomIdBody())! as RoomIdBody;
    case 'PostIdBody': return accessor(index, new PostIdBody())! as PostIdBody;
    case 'ApprovePostBody': return accessor(index, new ApprovePostBody())! as ApprovePostBody;
    case 'ApproveUserBody': return accessor(index, new ApproveUserBody())! as ApproveUserBody;
    case 'UpdateIdBody': return accessor(index, new UpdateIdBody())! as UpdateIdBody;
    case 'PhonePinBody': return accessor(index, new PhonePinBody())! as PhonePinBody;
    case 'RequestPinResetBody': return accessor(index, new RequestPinResetBody())! as RequestPinResetBody;
    case 'ConfirmPinResetBody': return accessor(index, new ConfirmPinResetBody())! as ConfirmPinResetBody;
    case 'RequestEmailChangeBody': return accessor(index, new RequestEmailChangeBody())! as RequestEmailChangeBody;
    case 'ConfirmEmailChangeBody': return accessor(index, new ConfirmEmailChangeBody())! as ConfirmEmailChangeBody;
    case 'PinResetResolveBody': return accessor(index, new PinResetResolveBody())! as PinResetResolveBody;
    case 'EmptyReq': return accessor(index, new EmptyReq())! as EmptyReq;
    default: return null;
  }
}
