// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

/**
 * Forgot PIN: identify account by phone; OTP is emailed if the account has an email on file.
 */
export class RequestPinResetBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RequestPinResetBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRequestPinResetBody(bb:flatbuffers.ByteBuffer, obj?:RequestPinResetBody):RequestPinResetBody {
  return (obj || new RequestPinResetBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRequestPinResetBody(bb:flatbuffers.ByteBuffer, obj?:RequestPinResetBody):RequestPinResetBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RequestPinResetBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

phoneNumber():string|null
phoneNumber(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
phoneNumber(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.RequestPinResetBody" {
  return 'mybroker.RequestPinResetBody';
}

static startRequestPinResetBody(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPhoneNumber(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, phoneNumberOffset, 0);
}

static endRequestPinResetBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRequestPinResetBody(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset):flatbuffers.Offset {
  RequestPinResetBody.startRequestPinResetBody(builder);
  RequestPinResetBody.addPhoneNumber(builder, phoneNumberOffset);
  return RequestPinResetBody.endRequestPinResetBody(builder);
}
}
