// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars */

import * as flatbuffers from 'flatbuffers';

import { ReqPayload, unionToReqPayload, unionListToReqPayload } from '../mybroker/req-payload';


export class RequestEnv {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RequestEnv {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRequestEnv(bb:flatbuffers.ByteBuffer, obj?:RequestEnv):RequestEnv {
  return (obj || new RequestEnv()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRequestEnv(bb:flatbuffers.ByteBuffer, obj?:RequestEnv):RequestEnv {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RequestEnv()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bodyType():ReqPayload {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ReqPayload.NONE;
}

body<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static getFullyQualifiedName(): "mybroker.RequestEnv" {
  return 'mybroker.RequestEnv';
}

static startRequestEnv(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBodyType(builder:flatbuffers.Builder, bodyType:ReqPayload) {
  builder.addFieldInt8(0, bodyType, ReqPayload.NONE);
}

static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, bodyOffset, 0);
}

static endRequestEnv(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishRequestEnvBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedRequestEnvBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createRequestEnv(builder:flatbuffers.Builder, bodyType:ReqPayload, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  RequestEnv.startRequestEnv(builder);
  RequestEnv.addBodyType(builder, bodyType);
  RequestEnv.addBody(builder, bodyOffset);
  return RequestEnv.endRequestEnv(builder);
}
}
