// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

/**
 * Authenticated: send OTP to the new address (SES).
 */
export class RequestEmailChangeBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RequestEmailChangeBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRequestEmailChangeBody(bb:flatbuffers.ByteBuffer, obj?:RequestEmailChangeBody):RequestEmailChangeBody {
  return (obj || new RequestEmailChangeBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRequestEmailChangeBody(bb:flatbuffers.ByteBuffer, obj?:RequestEmailChangeBody):RequestEmailChangeBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RequestEmailChangeBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

email():string|null
email(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
email(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.RequestEmailChangeBody" {
  return 'mybroker.RequestEmailChangeBody';
}

static startRequestEmailChangeBody(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEmail(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, emailOffset, 0);
}

static endRequestEmailChangeBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRequestEmailChangeBody(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset):flatbuffers.Offset {
  RequestEmailChangeBody.startRequestEmailChangeBody(builder);
  RequestEmailChangeBody.addEmail(builder, emailOffset);
  return RequestEmailChangeBody.endRequestEmailChangeBody(builder);
}
}
