// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class RoomIdBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomIdBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomIdBody(bb:flatbuffers.ByteBuffer, obj?:RoomIdBody):RoomIdBody {
  return (obj || new RoomIdBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomIdBody(bb:flatbuffers.ByteBuffer, obj?:RoomIdBody):RoomIdBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomIdBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.RoomIdBody" {
  return 'mybroker.RoomIdBody';
}

static startRoomIdBody(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRoomId(builder:flatbuffers.Builder, roomId:number) {
  builder.addFieldInt32(0, roomId, 0);
}

static endRoomIdBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomIdBody(builder:flatbuffers.Builder, roomId:number):flatbuffers.Offset {
  RoomIdBody.startRoomIdBody(builder);
  RoomIdBody.addRoomId(builder, roomId);
  return RoomIdBody.endRoomIdBody(builder);
}
}
