// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class SignInPhone {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SignInPhone {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSignInPhone(bb:flatbuffers.ByteBuffer, obj?:SignInPhone):SignInPhone {
  return (obj || new SignInPhone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSignInPhone(bb:flatbuffers.ByteBuffer, obj?:SignInPhone):SignInPhone {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SignInPhone()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

phoneNumber():string|null
phoneNumber(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
phoneNumber(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static getFullyQualifiedName(): "mybroker.SignInPhone" {
  return 'mybroker.SignInPhone';
}

static startSignInPhone(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPhoneNumber(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, phoneNumberOffset, 0);
}

static endSignInPhone(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSignInPhone(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset):flatbuffers.Offset {
  SignInPhone.startSignInPhone(builder);
  SignInPhone.addPhoneNumber(builder, phoneNumberOffset);
  return SignInPhone.endSignInPhone(builder);
}
}
