// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class UpdateProfileBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpdateProfileBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUpdateProfileBody(bb:flatbuffers.ByteBuffer, obj?:UpdateProfileBody):UpdateProfileBody {
  return (obj || new UpdateProfileBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUpdateProfileBody(bb:flatbuffers.ByteBuffer, obj?:UpdateProfileBody):UpdateProfileBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateProfileBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

username():string|null
username(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
username(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

photo():string|null
photo(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
photo(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

showContactSet():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

showContact():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isBrokerSet():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isBroker():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

brokerFeesSet():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

brokerFees():string|null
brokerFees(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
brokerFees(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

acceptedPsSet():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

acceptedPs():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "mybroker.UpdateProfileBody" {
  return 'mybroker.UpdateProfileBody';
}

static startUpdateProfileBody(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addUsername(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, usernameOffset, 0);
}

static addPhoto(builder:flatbuffers.Builder, photoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, photoOffset, 0);
}

static addShowContactSet(builder:flatbuffers.Builder, showContactSet:boolean) {
  builder.addFieldInt8(3, +showContactSet, +false);
}

static addShowContact(builder:flatbuffers.Builder, showContact:boolean) {
  builder.addFieldInt8(4, +showContact, +false);
}

static addIsBrokerSet(builder:flatbuffers.Builder, isBrokerSet:boolean) {
  builder.addFieldInt8(5, +isBrokerSet, +false);
}

static addIsBroker(builder:flatbuffers.Builder, isBroker:boolean) {
  builder.addFieldInt8(6, +isBroker, +false);
}

static addBrokerFeesSet(builder:flatbuffers.Builder, brokerFeesSet:boolean) {
  builder.addFieldInt8(7, +brokerFeesSet, +false);
}

static addBrokerFees(builder:flatbuffers.Builder, brokerFeesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, brokerFeesOffset, 0);
}

static addAcceptedPsSet(builder:flatbuffers.Builder, acceptedPsSet:boolean) {
  builder.addFieldInt8(9, +acceptedPsSet, +false);
}

static addAcceptedPs(builder:flatbuffers.Builder, acceptedPs:boolean) {
  builder.addFieldInt8(10, +acceptedPs, +false);
}

static endUpdateProfileBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUpdateProfileBody(builder:flatbuffers.Builder, id:number, usernameOffset:flatbuffers.Offset, photoOffset:flatbuffers.Offset, showContactSet:boolean, showContact:boolean, isBrokerSet:boolean, isBroker:boolean, brokerFeesSet:boolean, brokerFeesOffset:flatbuffers.Offset, acceptedPsSet:boolean, acceptedPs:boolean):flatbuffers.Offset {
  UpdateProfileBody.startUpdateProfileBody(builder);
  UpdateProfileBody.addId(builder, id);
  UpdateProfileBody.addUsername(builder, usernameOffset);
  UpdateProfileBody.addPhoto(builder, photoOffset);
  UpdateProfileBody.addShowContactSet(builder, showContactSet);
  UpdateProfileBody.addShowContact(builder, showContact);
  UpdateProfileBody.addIsBrokerSet(builder, isBrokerSet);
  UpdateProfileBody.addIsBroker(builder, isBroker);
  UpdateProfileBody.addBrokerFeesSet(builder, brokerFeesSet);
  UpdateProfileBody.addBrokerFees(builder, brokerFeesOffset);
  UpdateProfileBody.addAcceptedPsSet(builder, acceptedPsSet);
  UpdateProfileBody.addAcceptedPs(builder, acceptedPs);
  return UpdateProfileBody.endUpdateProfileBody(builder);
}
}
