// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { User } from '../mybroker/user';


export class UsersList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UsersList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUsersList(bb:flatbuffers.ByteBuffer, obj?:UsersList):UsersList {
  return (obj || new UsersList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUsersList(bb:flatbuffers.ByteBuffer, obj?:UsersList):UsersList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UsersList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

users(index: number, obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

usersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.UsersList" {
  return 'mybroker.UsersList';
}

static startUsersList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUsers(builder:flatbuffers.Builder, usersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, usersOffset, 0);
}

static createUsersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUsersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endUsersList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUsersList(builder:flatbuffers.Builder, usersOffset:flatbuffers.Offset):flatbuffers.Offset {
  UsersList.startUsersList(builder);
  UsersList.addUsers(builder, usersOffset);
  return UsersList.endUsersList(builder);
}
}
