// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class User {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):User {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUser(bb:flatbuffers.ByteBuffer, obj?:User):User {
  return (obj || new User()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUser(bb:flatbuffers.ByteBuffer, obj?:User):User {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new User()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

phoneNumber():string|null
phoneNumber(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
phoneNumber(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

photo():string|null
photo(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
photo(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

email():string|null
email(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
email(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastSeen():string|null
lastSeen(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastSeen(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

status():string|null
status(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
status(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

verified():string|null
verified(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
verified(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

showContact():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isBroker():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

brokerFees():string|null
brokerFees(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
brokerFees(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

acceptedPs():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "mybroker.User" {
  return 'mybroker.User';
}

static startUser(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addPhoneNumber(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, phoneNumberOffset, 0);
}

static addPhoto(builder:flatbuffers.Builder, photoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, photoOffset, 0);
}

static addEmail(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, emailOffset, 0);
}

static addLastSeen(builder:flatbuffers.Builder, lastSeenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, lastSeenOffset, 0);
}

static addStatus(builder:flatbuffers.Builder, statusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, statusOffset, 0);
}

static addVerified(builder:flatbuffers.Builder, verifiedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, verifiedOffset, 0);
}

static addShowContact(builder:flatbuffers.Builder, showContact:boolean) {
  builder.addFieldInt8(8, +showContact, +false);
}

static addIsBroker(builder:flatbuffers.Builder, isBroker:boolean) {
  builder.addFieldInt8(9, +isBroker, +false);
}

static addBrokerFees(builder:flatbuffers.Builder, brokerFeesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, brokerFeesOffset, 0);
}

static addAcceptedPs(builder:flatbuffers.Builder, acceptedPs:boolean) {
  builder.addFieldInt8(11, +acceptedPs, +false);
}

static endUser(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUser(builder:flatbuffers.Builder, id:number, nameOffset:flatbuffers.Offset, phoneNumberOffset:flatbuffers.Offset, photoOffset:flatbuffers.Offset, emailOffset:flatbuffers.Offset, lastSeenOffset:flatbuffers.Offset, statusOffset:flatbuffers.Offset, verifiedOffset:flatbuffers.Offset, showContact:boolean, isBroker:boolean, brokerFeesOffset:flatbuffers.Offset, acceptedPs:boolean):flatbuffers.Offset {
  User.startUser(builder);
  User.addId(builder, id);
  User.addName(builder, nameOffset);
  User.addPhoneNumber(builder, phoneNumberOffset);
  User.addPhoto(builder, photoOffset);
  User.addEmail(builder, emailOffset);
  User.addLastSeen(builder, lastSeenOffset);
  User.addStatus(builder, statusOffset);
  User.addVerified(builder, verifiedOffset);
  User.addShowContact(builder, showContact);
  User.addIsBroker(builder, isBroker);
  User.addBrokerFees(builder, brokerFeesOffset);
  User.addAcceptedPs(builder, acceptedPs);
  return User.endUser(builder);
}
}
