// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

export class VerifyOtpBody {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VerifyOtpBody {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVerifyOtpBody(bb:flatbuffers.ByteBuffer, obj?:VerifyOtpBody):VerifyOtpBody {
  return (obj || new VerifyOtpBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVerifyOtpBody(bb:flatbuffers.ByteBuffer, obj?:VerifyOtpBody):VerifyOtpBody {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VerifyOtpBody()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

phoneNumber():string|null
phoneNumber(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
phoneNumber(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

email():string|null
email(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
email(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

otp():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "mybroker.VerifyOtpBody" {
  return 'mybroker.VerifyOtpBody';
}

static startVerifyOtpBody(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPhoneNumber(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, phoneNumberOffset, 0);
}

static addEmail(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, emailOffset, 0);
}

static addOtp(builder:flatbuffers.Builder, otp:number) {
  builder.addFieldInt32(2, otp, 0);
}

static endVerifyOtpBody(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVerifyOtpBody(builder:flatbuffers.Builder, phoneNumberOffset:flatbuffers.Offset, emailOffset:flatbuffers.Offset, otp:number):flatbuffers.Offset {
  VerifyOtpBody.startVerifyOtpBody(builder);
  VerifyOtpBody.addPhoneNumber(builder, phoneNumberOffset);
  VerifyOtpBody.addEmail(builder, emailOffset);
  VerifyOtpBody.addOtp(builder, otp);
  return VerifyOtpBody.endVerifyOtpBody(builder);
}
}
